<?php

/**
 * @file
 * Hooks for the views_date_past_upcoming module.
 */


/**
 * Implements hook_views_data().
 */
function views_date_past_upcoming_views_data(): array {
  $data['views']['table']['group'] = t('Custom Global');
  $data['views']['table']['join'] = [
    '#global' => [],
  ];

  $data['views']['date_past_upcoming'] = [
    'title' => t('Date Past/Upcoming'),
    'help' => t('Calculates whether a date is upcoming or in the past.'),
    'field' => [
      'id' => 'date_past_upcoming',
    ],
  ];

  $data['views']['date_past_upcoming_sort'] = [
    'title' => t('Date Past/Upcoming Sort'),
    'help' => t('Sort by future dates first (ascending), then past dates (descending).'),
    'sort' => [
      'id' => 'date_past_upcoming_sort',
    ],
  ];

  return $data;
}
