views.field.past_upcoming:
  type: views_field
  label: 'Past/upcoming'
  mapping:
    label_upcoming:
      type: label
      label: 'Label for upcoming dates'
    label_past:
      type: label
      label: 'Label for past dates'
    label_ongoing:
      type: label
      label: 'Label for ongoing items'
    label_none:
      type: label
      label: 'Label when there is no date'

views.sort.past_upcoming:
  type: views_sort
  label: 'Past/upcoming'
